Sprint1/step3
olegbutrin/react-burger pull request #3
Opened 2021-12-12 03:16 UTC by olegbutrin

Переписал все на функциональные компоненты. 
Сейчас одновременно определены propTypes и Typescript правила для props. По мере освоения Typescript возможно отказаться от propTypes.

2021-12-13 00:57 UTC, grishbar requested changes
Проделана большая работа, но есть еще много мест, над которыми надо поработать: Подумай хорошо над хранением данных в компоненте, чтобы не перекладывать их постоянно между друг другом, и не дублировать код.

- [x] В proptypes не должно быть any все типы для пропсов компонентов должны быть полностью описаны.
- [x] Убрать создание функций в jsx
- [ ] Компоненты, которые зависят только от пропсов должны быть созданы в jsx а не пересоздаваться в компоненте при помощи функций
- [ ] Также функционал работает не совсем корректно, это конечно прикольно, что ты добавил функционал по добавлению ингредиентов в конструктор, но давай от него избавимся. Так как потом его нужно будет реализовывать совсем иначе. Также если хочешь его оставить, он работает не совсем корректно, не получается добавить несколько разных  начинок.

Удачи в рефакторинге

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +const __URL = "https://norma.nomoreparties.space/api/ingredients ";
`надо исправить`
имя переменной url слишком абстрактное, оно не показывает явно, что в ней лежит. Давай назовем как нибудь INGREDIENTS_URL

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +  });
`надо исправить`
давай переименуем переменную, dataState и data не отображают, то, что хранится в этих переменных, давай назовем как нибудь ingredientsState и вместо data ingredients

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +];
`можно лучше`
какое то не масштабируемо решение совсем получается, если появится новый тип придется в нескольких местах дорабатывать, и можно сделать эффективней заведи [Map](https://learn.javascript.ru/map-set)  где ключами будет тип, а значениями нужные данные

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +    }));
`надо исправить`
для чего эти строчки? Кажется их можно удалить и ничего не изменится

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +      )
`надо исправить`
При совершении запроса, он может успешно выполнится и вернуться не с 2xx статусом и соответственно он будет содержать не данные для ингредиентов, и не совсем очевидно, но такой запрос не попадет в блок catch, только если у тебя не случится какая то скриптовая ошибка тут, например  в json не полчится преобразовать, только тогда ты попадешь в catch. Соответственно тебе тут нужно если не [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) выкидывать ошибку, тогда тебя перекинет в блок catch

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +          ...prevDataState,
`надо исправить`
при ошибке при запросе, ты должен возвращать дефолтное состояние, а не предыдущее, так как не хочется в state хранить потенциально невалидные данные. Тут конечно, это не совсем актуально, так как этот useEffect будет выполняться только один раз, и тут при ошибке по сути и будет всегда дефолтное состояние.

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +    if (dataState.data.data.length) {
`надо исправить`
видишь, тут какое то дублирование data это надо исправить, также само название data слишком абстрактное, может содержать в себе все что угодно, от него тоже надо избавиться

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
кажется эта функция излишняя ее можно удалить

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +    let currentOrder: any = [];
`надо исправить`
это const

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +  });
`надо исправить`
зачем хранить тут модалку? она всегда должна быть одним и тем же реакт элементом с разными пропсами. А показываешь ты ее в зависимости от условия, которое тут хранишь.
Таже принято называть функцию которая меняет твою переменную состояния аналогично ей то есть должно быть modalState, setModalState

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
лишний код удалить, не нужно заране писать boilerplate дял функционала, который ты не знаешь, как потом будешь реализовывать, так как вероятней всего ты тут делаешь лишнюю работу, и только нагружаешь чтение кода

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +  const [selectedMain, setSelectedMain] = React.useState<string[]>([]);
`надо исправить`
у тебя получается слишком большой тяжелый сложный компонент много дублирования неявного хранения данных, ты перекладываешь из одного объекта данных в другой объект добавляя немного новых свойств в объект. Тяжело конкретно сформулировать, что тебе нужно сделать, чтобы твой код стал лучше. Для начала избавься от 45,46,47 строчки и храни ингредиенты только в одном месте, старайся делать так, чтобы у тебя всегда было как можно меньше источников данных.

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +    );
`надо исправить`
модалка постоянный компонент, не нужно ее постоянно пересоздавать

2021-12-13 00:57 UTC, grishbar commented on src/components/app/app.tsx
> +      );
`надо исправить`
тут также заведи просто две  модалки и показываю нужно в зависимости от условия

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +  };
`надо исправить`
не надо выносить создание компонента, это обычный компонент с разными пропсами, перенеси его в jsx

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +  };
`надо исправить`
думаю сам видишь, что это дублирование кода, избавься от него

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +  };
`надо исправить`
видишь, какая тяжелая логика получается, просто для подсчета суммы ингредиентов, если бы у тебя был просто массив со всеми ингредиентами конструктора, то тут бы одной строчкой при помощи [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) посчитал, подумай как сделать более простые и явные объекты для хранения данных и корректно их передавай

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.tsx
> +  };
`надо исправить`
во первых orderList это const,  также тут можно одной строчкой

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/components/burger-contents-item/burger-contents-item.tsx
> +        }}
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/components/burger-contents/burger-contents.tsx
> +          if (dataItem) {
`надо исправить`
вот здесь ты делаешь лишнюю работу почему бы не хранить в productsOrder объект с нужными данными, тогда бы не нудно было бы лишний поиск делать.

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-constructor/components/burger-contents/burger-contents.tsx
> +const BurgerContents = (props: {
`надо исправить`
надо избавиться от этой функции и выводить все в jsx

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  selectCallback: PropTypes.any,
`надо исправить`
это можно типизировать

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-box/ingredient-box.tsx
> +  itemRef: any;
`можно лучше`
 у тебя нигде не должно быть any, но сейчас у тебя должны быть типизированы только props у компонентов, так, что ок

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-box/ingredient-box.tsx
> +  selectIngredientCallback: PropTypes.any,
`надо исправить`
а вот propTypes должны быть типизированы корректно, так, что обрати внимание, чтобы нигде не было в них any

2021-12-13 00:57 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-preview/ingredient-preview.tsx
> +      }}
`надо исправить`
тут тоже надо убрать создание функций внутри jsx

2021-12-13 00:57 UTC, grishbar commented on src/utils/types.ts
> +// }
`надо исправить`
комментарии которые не документируют дальнейший код (не говорят, что будет происходит в последующих строчках под ними) должны быть удалены

2021-12-13 22:16 UTC, olegbutrin commented
Функционал по добавлению ингредиентов в бургер оставил (в основном, для тестирования), но сделал простым массивом ингредиентов. В логике добавления есть ограничение на количество ингредиентов разного типа.

Убрал все PropTypes.any, кроме определения ref. Какие бы рецепты определения не пробовал, регулярно выкидывается ошибка.

Все колбеки с параметрами вынес в константы. Я так понимаю, проблема в том, то стрелочные функции, задаваемые внутри колбеков, не убираются при размонтировании компонента?

2021-12-14 02:06 UTC, grishbar requested changes
Проделано много работы, проект стал лучше, но все еще очень много мест для доведения проекта до ума. Во-первых, давай избавимся от всего функционала, который ты придумал, и сделаем все исключительно согласно поставленному заданию, иначе на следующих этапаах тебе все раавно придется от него избавляться, потому что там его нужно будет реализовывать кардинально иначе. Если все таки настаиваешь, на то, чтобы его оставить, то поправь все согласно комментариям "надо исправить" и обрати внимание, что в текщем виде функионал совсем не работает, я не могу добавить несоклько ингредиентов разных, у меня все ломается, не работает очистка заказа после нажатия на кнопку и другое (все дело в том, что даешь неуникальный ключ ингредиентам, которые добавляешь в конструктор). Далее везде у тебя долдны быть корректно описаны типы, элементы которые отображаются условно (модалка) должна быть в jsx и условно показываться, и принимать разные children в зависимости от модалки (можно завести три модалки в app.tsx с разными пропсами и children).

Тебе предстоит еше большая работа, надеюсь ты справишься, удачи

2021-12-14 02:06 UTC, grishbar commented on src/components/app-header/components/menu-button/menu-button.tsx
> +  };
`надо исправить`
совсем не понятно, что такое callback и что такое clickFn, нужно дать этим переменным осмысленные названия

2021-12-14 02:06 UTC, grishbar commented on src/components/app-header/components/menu-button/menu-button.tsx
> +      style={{ order: order }}
`можно лучше`
инлайновые стили это всегда [очень плохо,](https://htmlacademy.ru/blog/boost/frontend/inline#:~:text=С%20inline-стилями%20немного%20иначе,-правило%2C%20отнимает%20немало%20времени.) так как их тяжело переопределять, и тяжело маасштабировать приложение из за них, переделай пожалуйста так, чтобы их не пришлось использовать

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +      let startedIngredients: IIngredientData[] = [];
`надо исправить`
это const

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
этот метод совсем тяжелый его очень сложно понять, лучше вобще избавься от него, так как такой функционал нам не нужен или перепеши его, тут все делается в одну строчку

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +  }, [ingredientsState.ingredients]);
`надо исправить`
этот метод аналогично практически нечитаемый, у меня ушло значительное количество времени, чтобы прочитать и разобраться, что же ты все таки пытаешься сделать и почему именно так. От этой функции тоже надо избавиться, или перепиши ее, делается также в одну строчку.
подсказка: просто заведи переменную initialState и присваивай ее здесь и в методе выше

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
твоя модалка должна быть компонентом, который мы условно показываем, ее не надо где то хранить и менять постоянно и пересоздавать

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
эта функция тоже очень тяжело воспринимаема, все что тебе надо сделать взять массив и положить в него новый элемент, зачем оборачивать какой то сложной, неявной логикой. Я ни в коем случае не против инициативы, проактивности, добавления индивидуальности проекта, но в пределах разумного, без фанатизма. Удали этот метод тоже или перепиши, чтобы он был в одну строчку (в массив ингредиентов кладешь новый ингредиент).

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +  };
`надо исправить`
это removeIngredient

2021-12-14 02:06 UTC, grishbar commented on src/components/app/app.tsx
> +    let selIngrs = [...selectedIngredients];
`надо исправить`
это const

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-constructor/components/burger-contents-item/burger-contents-item.tsx
> +      : undefined;
`надо исправить`
эта функция должна быть навешана на иконку удалить, которую у булок ты не отображаешь

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-constructor/components/burger-contents-item/burger-contents-item.tsx
> +      extraName = " (верх)";
`надо исправить`
тут должно быть низ

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  };
`надо исправить`
не надо писать 10 строчек неявной логики, когда можно просто в одну строчку создать массив или Map, где у тебя будет соотноситься тип с рефом

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  selectCallback: (...args: any[]) => void;
`надо исправить`
если взялся за typescript надо типизировать пропсы функции, если не можешь на typescript типизировать, сделай на propTypes

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    }
`можно лучше`
```
      ref?.current?.scrollIntoView({
        behavior: "smooth",
        block: "start",
        inline: "start",
      });
```

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +      window.scrollTo(0, 0);
`надо исправить`
эта строчка только портит функционал, ее надо удалить

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +    if (ref != null) {
`надо исправить`
дважды проверяешь, что ref не null, здесь и в самой функции

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +        )}
`надо исправить`
чтобы просто отрисовать три таба, ты написал 22 строчки, с созданием функции скролла для каждого таба, хотя она должна быть одна для всех трех, надо все переписать, чтобы у тебя был один заранее понятный объект по которому ты мапишься, и отрисовываешь три таба, никакой больше логики тут быть не должно

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +        )}
`надо исправить`
тут то же самое, что хранится в этом массиве - [...props.ingredientTypes.keys()] , вобще непонятно, у тебя есть уже три объявленных рефа у тебя есть три типа, соедини одно с другим в одном понятном объекте, и сделай красиво.

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  ingredientTypes: PropTypes.instanceOf(Map),
`надо исправить`
надо описать какие объекты хранятся в твоей мапе, иначе никаких плюсов от описания типов ты не получаешь

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-box/ingredient-box.tsx
> +          ).length;
`надо исправить`
подсчет каунтера должен быть в компоненте, а не в jsx, старайся писать код так, чтобы в jsx у тебя не было никакой логики совсем, во первых так читается намного чище и проще, во вторых хоть и незначительно, но ты нагружешь свое приложение постоянным вызовом js и созданием объектов в jsx, и реакт не может корректно сравнивать состояние твоего компонента, нужно ему его пересивывать его или нет, так как ты объекты создал в jsx а не в компоненте.
Также подсчет counter надо делать при помощи [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-preview/ingredient-preview.tsx
> +      onClick={clickFn}
`надо исправить`
[нельзя создавать функции внутри jsx](https://qastack.ru/programming/36677733/why-shouldnt-jsx-props-use-arrow-functions-or-bind), это плохо влияет на производительность, и не [рекомендуется разработчиками реакта](https://ru.reactjs.org/docs/faq-functions.html)

2021-12-14 02:06 UTC, grishbar commented on src/components/burger-ingredients/components/ingredient-preview/ingredient-preview.tsx
> +      {props.count > 0 ? <Counter count={props.count} size={"default"} /> : ""}
`надо исправить`
тут тебе не нужен тернарный оператор, достаточно будет &&

2021-12-14 02:06 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.tsx
> +  children: any;
`надо исправить`
пропсы компонентов, должны быть полностью и корректно описаны, так сказано в твоем задании

2021-12-14 02:06 UTC, grishbar commented on src/components/modal-overlay/modal-overlay.tsx
> +      {props.children}
`надо исправить`
компонент modal-overlay не должен принимать children, это делает, только компонент modal, в этом компоненте, у тебя просто верстка, + обработка события по клику на нему и все, далее этот компонент ты заимпортируешь в компоненте modal и отрисуешь там

2021-12-14 02:06 UTC, grishbar commented on src/components/modal/modal.tsx
> +    if (e.keyCode === 27) {
`надо исправить`
"магических" чисел быть не должно, вынеси это число в отдельную переменную, и дай ей осмысленное назваание

2021-12-14 02:06 UTC, grishbar commented on src/components/modal/modal.tsx
> +        }}
`надо исправить`
тут тоже убрть создание функций из jsx

2021-12-15 22:23 UTC, merged